name: CI/CD for Timeless Frontend

on:
  push:
    branches: [main, develop]
    paths: ['frontend/**']
  pull_request:
    branches: [main]
    paths: ['frontend/**']

defaults:
  run:
    working-directory: ./frontend

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Run test coverage
        run: npm run coverage
        continue-on-error: true
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Netlify
        if: github.ref == 'refs/heads/main'
        run: echo "Deployment automatically triggered by Netlify on push to main branch"